### ISSUE TITLE
Implement custom formatting

### ISSUE THREAD

**Issue by perpk** [perpk/json-xform#26]
Users should be able to provide custom formatting on target fields. An option would be to accept a function mapping on an additional property which addresses the field addressed in the mapping.

**Comment by rmtuckerphx** [comment]
I'm looking for a way to specify a template string that will be used when setting a value.

If we had the source:
```
{
  "$data": {
    "firstName": "Mark",
    "lastName": "Tucker",
  }
}
```

And we wanted the target to be:
```
{
  "name": "Mark Tucker"
}
```

We could use a mapping like this:
```
{
    "fieldset": [
        {
            "to": "name",
            "toTemplate": `${$data.firstName} ${$data.lastName}`
        }
    ]
}
```

Thoughts?

**Comment by perpk** [comment]
Hey @rmtuckerphx! Thanks, I'll play around a bit and check your suggestion as well and will come back with more asap.
