### ISSUE TITLE
Map based on value of source json

### ISSUE THREAD

**Issue by royteeuwen** [perpk/json-xform#47]
I am trying to map a json based on the value, is this something that is feasible?

source Json
```
{
    "content": [
        {
            "type": "text",
            "value" :"My Text"
        }
    ]
}
```

target Json
```
{
    "content": [
        {
            "text": {
                "value" :"My Text"
            }
        }
    ]
}
```

I see you use json path, and in there you would be able to make the selection $.content[?(@.type=="text")]

**Comment by perpk** [comment]
Hey @royteeuwen sorry for the extra-late response on this. Been struggling with other issues in the meantime. However, thanks for spotting that. I think I'll get this variation of the mapping in a new release probably 1.3.0.
Cheers

**Comment by royteeuwen** [comment]
No worries, it’s an open source project. If I had more time myself i could also have contributed it 😅! Thanks for the effort :)
