### ISSUE TITLE
unable to change the key of the object

### ISSUE THREAD

**Issue by pavithraJayanna** [perpk/json-xform#48]
I am trying to modify  a  value inside an object , i am trying avoid fieldset for each item in an object . 

source Json
{
    "cases": 
        {
            "caseId": "1",
            "caseStatus" :"Active",
           "name" : "xxx"
        }
}

target JSON 
{
    "cases": 
        {
            "caseId": "1",
            "status" :"Active",
           "name": "xxx"
        }
    
}

here i am trying to avoid  three time filedset  for each item in a cases object , Any suggestion on this?.

**Comment by perpk** [comment]
Hi @pavithraJayanna and sorry for the late response. The answer is no, you can't avoid having three fieldsets in that case. Each field transformation rule must have its own fieldset in the mapping.

**Comment by perpk** [comment]
Since there's no action to take on the question in terms of a fix or an improvement this issue is closed. Since suggestions are very welcome please feel free to either reopen the same or open another one. I'm currently actively working on this project so it won't take much time to respond.
Cheers!
