### ISSUE TITLE
Mapping of collections/arrays with fromEach inherits structure from source

### ISSUE THREAD

**Issue by konstantinos-perperidis** [perpk/json-xform#6]
It should be possible to map fields to the target w/o inheriting the source structure.
e.g. from
`{
  collection: [
   { fieldUno: 1, fieldDuo: 2 }
}`
to
`{
  fieldUno: 1,
  fieldDuo
}`
so actually a possibility to 'flatten' the structures to the produced target object.

**Comment by perpk** [comment]
Test in https://github.com/perpk/json-xform/commit/f36169700792f53d1ec51e30bc5acac2ce6d07d4 to verify as well to add further tests to specify the desired behaviour more precise.

**Comment by perpk** [comment]
Done with PR #12
