### ISSUE TITLE
Transforming an Array of Objects into an Array of Primitive Values

### ISSUE THREAD

**Issue by tedraykov** [perpk/json-xform#71]
An example of a transformation I would want to make is the following:

### Input
```json
{
  "users": [
    {
      "name": "Joe",
      "age": 21
    },
    {
      "name": "Lucy",
      "age": 24
    },
  ]
}
```

### Output
```json
{
   "ages": [ 21, 24]
}
```

What would a transformation schema for such a use case would look like and if it's not a supported operation I might be willing to contribute.

**Comment by perpk** [comment]
Hey @tedraykov ! Truth be told, the case you're mentioning is not supported currently. You're very welcome to contribute if you want to!

**Comment by perpk** [comment]
There is an issue #68 available to address this case.

**Comment by perpk** [comment]
Hey @tedraykov I just had a little time to look into the question again. I fiddled around with the mapping while trying to set the base to implement the appropriate login in an additional test and came up with this which also works in the currently released version:
```javascript
// Source to transform
    const source = {
      users: [
        {
          name: 'Mike',
          age: 31
        },
        {
          name: 'Aaron',
          age: 42
        },
        {
          name: 'Eddie',
          age: 38
        }
      ]
    }
```

```javascript
// XForm Template
    const xFormTemplate = {
      fieldset: [
        {
          fromEach: {
            field: 'users',
            to: 'ages',
            flatten: true,
            fieldset: [
              {
                fromEach: { field: 'age' }
              }
            ]
          }
        }
      ]
    }
```

```javascript
// Result after execution
    const target = {
      ages: [31, 42, 38]
    }
```
